### ISSUE TITLE
Example script returns threading issue

### ISSUE THREAD

**Issue by c-herff** [labstreaminglayer/ezmsg-lsl#18]
When trying to run the LSLInletExample.py I get the following error, independent of python version.

> Exception has occurred: TypeError
>cannot pickle '_thread.lock' object
>  File "C:\workspace\closed-loop-speech-playground\LSLInputExample.py", line 45, in main
>   system = LSLDemoSystem()
>File "C:\workspace\closed-loop-speech-playground\LSLInputExample.py", line 53, in <module>
>    typer.run(main)
>TypeError: cannot pickle '_thread.lock' object

**Comment by cboulay** [comment]
Thanks for the report. I was able to reproduce. I'm not sure when that changed but I'll look into it.

Also check out tests/test_inlet.py which is still running and passing.

**Comment by cboulay** [comment]
I refactored the example script and now it runs. See the latest in the `dev` branch.

I just ran into a race condition in the outlet example script and test so I will fix those before creating a new release.

**Comment by c-herff** [comment]
That was amazingly fast. Thank you!

**Comment by cboulay** [comment]
ezmsg-lsl v1.2.1 now released on pypi.

The example script doesn't live in the package so the release doesn't really matter for your original issue, but this is just an FYI that the outlet-clock sync race condition is now fixed.

Cheers.

**Comment by c-herff** [comment]
Just as an FYI:
If I use `ez.run(components=comps, connections=conns)`, everything works fine, but with 
`def network(self) -> ez.NetworkDefinition:
        return ((self.SRC, self.PRINTER.INPUT),)`
I get the thread.lock error again.

**Comment by cboulay** [comment]
OK thanks. I'll create an minimum example and raise the issue in the core ezmsg repo. I'm not yet sure if it's LSL-specific. I'm not sure why it would be.

**Comment by cboulay** [comment]
@c-herff , please let me know if you are able to test the branch in https://github.com/ezmsg-org/ezmsg-lsl/pull/24 to see if the root problem is now fixed for you and you are able to pull data properly. If yes then I'll merge and make a new release.

**Comment by c-herff** [comment]
I get a new error stating

> Exception has occurred: AttributeError
> 'LSLInletUnit' object has no attribute 'encode'

**Comment by cboulay** [comment]
Unfortunately I can't reproduce that. Nor does the word `encode` appear anywhere in ezmsg-lsl or ezmsg core as an attribute.

I added a new test, which should cover what you're describing: https://github.com/ezmsg-org/ezmsg-lsl/blob/23-cannot-deepcopy-lslinletunit-or-lsloutletunit/tests/test_inlet.py#L63
And it seems to pass: https://github.com/ezmsg-org/ezmsg-lsl/actions/runs/11929358616

The test does not connect to an outlet, so it's not a perfect reproduction, but I don't see how `encode` would be requested of the unit.

**Comment by c-herff** [comment]
Weird, I think the problem might arise from the actual outlet, but I can't quite trace where the encode comes from, either. Will have a look at this later. Thanks for all your help.

**Comment by cboulay** [comment]
Next time I'm connecting LSL streams to ezmsg I will look for this explicitly. Thanks for your patience.
